name: pokefront
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  http: ^1.1.0
  google_fonts: ^5.1.0
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_staggered_animations: ^1.1.0
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
